# Run with:
# aws ecs run-task --cli-input-yaml "$(cat tasks/users-create.yaml)"
taskDefinition: "airflow-standalone-task"
cluster: "airflow"
count: 1
capacityProviderStrategy:
  - capacityProvider: "FARGATE"
platformVersion: "1.4.0"
networkConfiguration:
  awsvpcConfiguration:
    subnets:
      - "ADD THIS YOURSELF"
    securityGroups:
      - "ADD THIS YOURSELF"
    assignPublicIp: ENABLED
# Custom command options
overrides:
  containerOverrides:
    # Gotcha: name must correspond to an existing container name in the standalone task definition
    - name: "airflow"
      command:
        [
          "users",
          "create",
          "--username",
          "airflow",
          "--firstname",
          "airflow",
          "--lastname",
          "airflow",
          "--password",
          "airflow",
          "--email",
          "airflow@example.com",
          "--role",
          "Admin",
        ]
      cpu: 512
      memory: 1024
  cpu: "512"
  memory: "1024"
